/**
 * Copyright (c) 2024 Agua Games. All rights reserved.
 * Licensed under the Agua Games License 1.0
 * 
 * @file WavePhysicsNode.h
 * @brief WavePhysicsNode is a class that handles energy transfer and transformation in the engine.
 * The name may mislead some users into thinking WavePhysicsNode has a very narrow scope, but in fact the choice of the name is intentional, to make clear our
 * paradigm regarding physics. We could have an even more telling name, like WaveFieldPhysics, but we must also had to consider "marketing", appeal, etc.
 * Computer graphics, historically, has not evolved with "immanent" physics properties as a core thing - you can easily notice the signs of this in the fact
 * that most fundamental data structures, like the vertex, were never designed holding physics attributes in them. This is a testament to the disproportionately
 * visually oriented paradigm that evolved in the industry, in the efforts to model realistic worlds - in fact, a fundamental deficiency of the evolution of its
 * design vision.
 * So, keep this in mind, while you follow our design and implementation. That we try our best to work around this fact, trying to "crawl" into the core
 * data structures, since the Vulkan core, to gain a better place in the sun for Physics. Not like a "fragile" messed mix of short-sighted fixes, but as a
 * more structured and "feeling automatic", "for free" design and more tightly coupled with the core player experience, more coherent, more consistent, more 
 * elegant whenever possible also.
 * 
 * ARCHITECTURAL NOTES:
 * - Main elements, entities in the WavePhysicsNode system:
 *          - Field: Energy distribution in space, be it potential or converted: kinetic/momentum, etc.
 *          - Dimensional Energy: Energy represented as a 4D vector (spectral components), which we can project to scalar when needed for simple calculations, 
 *          rich interaction possibilities between components.
 *          - Wave: Energy excitation/perturbation/radiation in a field
 *          - Wavefront: Wave propagation path. In general we are referring to the Wavefront Tracker: the point in the field where the excitation value of the 
 *          wave/continuum crossed the limiar threshold - manifesting energy enough to be considered a wavefront.
 *          - Short-lived Particle/Wavefront Tracker: A computational marker for wavefront tracking. In general, referring to "short-lived waves" - waves whose
 *          dissipation is so fast/short lived that it's not worth tracking them any longer. They're meant to contribute to intense and short-lived energy 
 *          transfer in phenomena interesting for realtime games, like impacts, explosions, combustions, heating, transfer of kinectic energy, heat, sound
 *          generated by fluid compression/push, shockwaves, luminous phenomena, ionization (plasma filaments, fields), in various degrees of intensity and 
 *          wavefront sampling density. In the technical side, what we model them to go through is actually physics events like particle decay, pair production, 
 *          change of energy state (energy signature, like "it's a quark", "a photon", "a boson"), change of atomic nuclei/signature, etc.
 *          - Energy Manifestation: The way energy is expressed in the system. It can be kinetic, thermal, particle, wave (radiation, electromagnetic plus other
 *          known and support for custom/exoteric - 'exoteric' in the sense of the frontier of physics, extreme physics, astrophysics), field.
 *          - Impact/Collision: Energy transfer between objects. We use these names for easy recognition by users, familiarity, but conceptually we see these
 *          events much more like energy transfer events and also as some sort of temporary entanglement/ressonance/composition, like we see in standing waves, 
 *          wave superposition/composition, quantum physics: their phases interact, ressonate, modulate one another, based on their characteristics.
 *          Like energy rays crossing each other after being emitted: the point where they intertwine will manifest the result of their interaction, in general
 *          manifesting added energy, change of energy state, energy level in that region - like solving their wave-like superposition. It can go from microwave
 *          ressonator devices for game weapons to solving of car crashes, explosions, crumbling of buildings, shock between astrophysical bodies, quasars, etc.
 *          - Dimension: a set of values seem as  whole. The most defined, "stable", sampled stretches of them can be also seen as states - like in "the states 
 *          of matter", or in particle categories (neutrino, photon, boson, etc.).
 *          - Local Domain, Global Domain: We separate the domain/context of the system into two main categories.
 *          The Local Domain is used for further detailed, fine-grained solving. Also in scenarios where we may want to "isolate"/contain a system and its internal
 *          dynamics for the sake of making it possible to simulate such a system in realtime, performance-wise - electromagnetic fields, plasma-like fields,
 *          including vast ones like nebulas, but also very practical ones for games and other apps, like a battle arena sector (so sectors can be toggled on/off), 
 *          including also, possibly, exotic physics scenarios/systems - like the horizon of a black hole, etc. This means, naturally, that we may want to set
 *          some or all physics rules/laws as custom ones, to be different in a given local domain. Think of the various local domains as the branches in a tree,
 *          nodes in a node graph - in fact, this system will be designed analogous to the Scene Graph paradigm. A Local Domain would then be akin to a Layer in
 *          a usd scene composition. And this also means we leverage this granular, branching, already fractal structure to selectively load/unload and update 
 *          domains as needed, with LOD strategies, streaming, etc.
 *          The Global Domain is where we can have more general and pervasive, simple, straightforward physics, like general gravity, management of and state
 *          keeping, sync, of collisions, etc.
 *          Bonds, Links: we try to model and simplify otherwise complex and ultra-detailed physics interactions, from large scale systems to very small ones
 *          (specially useful for these last ones) using the concept of bonds and links. Strong stable electromagnetic bonds, for instance, or the energy involved,
 *          in "potential form", not released, required to break a stable bond. Matter, solid volumes are some obvious examples. Then shattering, destruction,
 *          fracturing become events which involve and require imense amounts of energy, releasing proportional amounts of energy, in various manifestation types,
 *          until all that energy is spent, finally dissipated and reabsorbed by the environment/system. That means, naturally, automatically, that the most
 *          still, static scenarios are the ones that require the least amount of processing but at the same time the ones which ironically are the most energy
 *          intense - imense amounts of energy is involved to keep them so static, and all that energy is there, waiting to be released.
 *          - Physics Thread/Physics Update: the physics solving, the solving of so many complex and dynamic elements mean we need to have a dedicated thread,
 *          also leverage multi-threading in it (with proper sync objects, of course). From the perspective of the Physics engine, subsystem, it is indeed the
 *          most fundamental core structure in the engine. All interactions emerge from its existence - the less hardcoded and scripted, the more this is true.
 *          It's as if the gameplay thread is mostly "fake" (in the sense of reflecting the real world), scripted, non-spontaneous: it's most like a "force of will"
 *          factor, a wishlist. While the physics thread and the physics system are much more complex and nuanced, dynamic and emergent. What prevents us from
 *          letting it spread more in realtime is of course performance constraints. And in Hydragon we have the proper harmonic mechanisms to gracefully lead
 *          the possible emergent scenarios to fruitful, interesting ones - e.g. the PatternOrchestrator.
 * 
 * - Spatial Partitioning: Grid-based division for parallel compute, Local space calculations, Neighbor search optimization. Adaptive granular refinement of these
 * grids, for further optimization (they can go from very sparse to very dense, depending on the needs of the simulation). Irregular grids for complex and exotic 
 * shapes, dimensional geometries.
 * - Selective Physics: Priority-based simulation. LOD for physics calculations, Distance-based activation.
 * - Energy Conservation: Track energy states, Optimize transfer calculations, Handle dissipation efficiently.
 * - Energy Manifestation: State transitions, Conservation rules, Dissipation patterns.
 * - Constraint Solving: Parallel constraint resolution, Iterative refinement, Stability maintenance.
 * - Coherent Memory Patterns: Buffer compaction, Cache optimization, Memory alignment.
 * - Compute Scheduling: Load balancing, Work distribution, Dependency management.
 * - Hybrid approach: Use Vulkan for real-time deformation, Taichi for complex scenarios, Blend between approaches based on needs.
 * - Efficient parallel processing, Selective physics simulation, Visual accuracy over physical accuracy, Scalable performance, High-quality results.
 * - Wave-Based Modeling: Uses wave functions as primary representation, Converts to particles only when needed, Maintains energy conservation.
 * - Adaptive precision using exponential encoding, Dimension reduction where possible, Local space calculations, Wavelet compression.
 * - Smart Memory Management: Compact struct layouts, Bit-field usage for quantized values, Adaptive grid refinement.
 * - Physics Approximation: Energy-based approach instead of direct forces, Wave propagation for continuous effects, Local space optimization.
 * - Energy Transfer System: Energy is never lost, only transformed, Automatic spawning of appropriate reactions based on thresholds, Different manifestation 
 * types (kinetic, thermal, particles, etc).
 * - Adaptive Precision: Dynamic bit depth based on energy magnitude, Higher precision for high-energy regions, Memory optimization for low-energy areas.
 * - Reaction System: Automatic effect spawning based on energy thresholds, Configurable reaction templates, Scale effects based on energy magnitude.
 * - Optimization Features: Progressive quantization levels, Wavelet compression with variable precision, Efficient memory usage for different energy manifestations.
 * - Sparse Particle System: Optimized storage with bit-packed flags, Distance-based culling, Minimum energy thresholds for early termination.
 * - Energy Propagation: Sphere of influence calculation, Energy transfer through space, Customizable falloff curves, Wave/field contribution integration.
 * - Multi-sampling System: Octave generation for detail enhancement, Energy scaling per generation: Controlled spawning based on importance. 
 * - Trajectory System: Multiple path types (linear, ballistic, spiral), Field-guided motion, Collision energy transfer.
 * - Optimization Features: Sparse sampling by default, Optional multi-sampling for important events, Early culling of low-energy particles, Packed data structures.
 * - Wave-Centric Approach: Uses "particles" merely as computational markers for wavefront tracking, Focuses on wave properties (amplitude, frequency, phase) rather 
 * than particle properties,Handles proper wave behavior (interference, superposition, attenuation).
 * - Field Integration: Treats each "particle" as a wave contribution point, Computes field strength through wave superposition, Handles medium transitions and 
 * field interactions.
 * - Energy Propagation: Models energy transfer as wave propagation, Accounts for medium properties (attenuation, dispersion), Handles wave-field interactions.
 * - Optimization: Uses short-lived markers to track wave peaks efficiently, Adapts precision based on energy levels, Maintains the sparse sampling approach while 
 * modeling continuous phenomena.
 * - Frequency Bands: Models the entire electromagnetic spectrum, Maps frequencies to physical effects, Includes thresholds for different interaction types.
 * - Interaction Effects: Ionization potential, Mutation probability, Decay chain reactions, Material penetration depth.
 * - Chain Reactions: Higher frequencies can trigger particle decay, Secondary radiation waves, Probability-based chain reactions.
 * - This naturally models phenomena like: Radiation shielding (penetration depth), Nuclear decay chains, Ionizing vs non-ionizing radiation, Quantum effects at 
 * high energies.
 * - Dimensional Energy: Energy represented as a 4D vector (spectral components), Can project to scalar when needed for simple calculations, Rich interaction 
 * possibilities between components.
 * - Modulation Field: 4D noise field (3D space + energy dimension), Warping based on energy levels, Multi-octave sampling for different scales, Cached regions 
 * for optimization.
 * - Wave-Field Interaction: Non-linear modulation effects, Energy-dependent wave behavior, Quantum effects at high energy levels, Propagation through energy landscape.
 * - Optimization Features: Cached sampling for frequently accessed regions, Adaptive step size based on energy levels, Scalar projection for simple calculations. 
 * - This creates interesting emergent behaviors: Waves can "resonate" with certain energy levels in the field, High-energy waves can "tunnel" through low-energy regions, 
 * Field modulation can create localized high-energy phenomena, Natural emergence of quantum-like behaviors at high energies.
 * - Domain Management Strategies: Streaming Domains: Like the chunks in OpenWorldExample.cpp, but for physics. Priority-based Processing: Similar to StreamingControlState
 * Dynamic LOD System: Based on WaveletMeshNode.h's approach.
 * - Edge Case Opportunities: High-energy concentrations could create temporary "anomalies" (gameplay features), Solver boundary interactions might generate interesting 
 * interference patterns Numerical "instabilities" could be channeled into visual effects.
 * 
 * Physics System Comparison:       Runtime Memory, MB	                    VRAM Usage, MB	            Binary Size, MB	            Relative Performance
 * 
 * Bullet Physics	                50-150	                                N/A	                        2-5	                        1.0x (baseline)
 * PhysX	                        100-300	                                50-150	                    8-15	                    1.2x
 * Havok	                        80-200                                  N/A	                        5-10	                    1.1x
 * Hydragon WavePhysics	            15-60                                   10-40                       3-6                         2.0-3.0x
 * 
 * Latest (theoretical) improvements shows:
 *
 * ~50% reduction in runtime memory usage through batch processing and compression
 * ~50% reduction in VRAM usage through field grid optimization
 * No significant change in binary size
 * ~30% performance improvement due to SIMD-friendly batch operations and better cache utilization
 * 
 * High Activity Zone │ Medium Activity       │ Low Activity Zone
 * ───────────────────┼───────────────────────┼───────────────────
 * 32-bit precision   │ 16-bit                │ 8-bit
 * Full update rate   │ 1/2 rate              │ 1/4 rate
 * All effects        │ Major effects         │ Essential only
 * Cached results     │ Partial cache         │ Fully cached
 * 
 * Active Domains     │ Ready Queue           │ Dormant
 * ───────────────────┼───────────────────────┼────────────
 * Full simulation    │ Physics state cached  │ Serialized
 * Real-time updates  │ Quick activation      │ Disk stored
 * Memory resident    │ Memory mapped         │ Compressed

 * Level 1: Local optimizations (per solver)
 * ↓
 * Level 2: Domain-level caching & streaming
 * ↓
 * Level 3: Global system management
 * ↓
 * Level 4: Emergency fallbacks
 * 
 * TODO:
 * - We'll start from the core conceptual elements, data structures and dynamics (fields, potential wells, energy conservation principles, wave-field interaction,
 * excitation dynamics), but then later we'll gradually incorporated layers of physics features towards the more superficial layers - like rigid body dynamics,
 * character, environment, etc. In that moment, for instance for rigid bodies, we may incorporate Bullet Physics, if we deem appropriate enough.
 * - Complete WavePhysicsSolver implementation
 * - Implement Vulkan-style configuration system
 * - Add methods for inter-solver communication
 * - Implement quantum effects handling
 * - Decide if we're going to create the Physics submodule from scratch, using Compute, etc, or if we're going to use a third-party physics library, like Taichi.
 * Or if we're going to use both, toggling at will, in a hybrid approach.
 * The idea of first concentrating on the core design of the physics system is not only the obvious way to do it but also to approach the physics side of the engine in a
 * way that hopefully it will lead to emergent physics behaviors, interactions - less work for the user and for us, more marveling at spontaneous phenomena, etc. We'll
 * profit from the fact that we don't have to prove anything or beat competitors: there's already a lot of good physics engines out there, and we're not specialists in
 * this field also. It will be more of a rich experimentation and discovery process, and we'll be able to learn a lot from it.
 * - The implementation is meant to be lightweight, efficient, and modular enough so that even WavePhysicsNode being used as a singleton, adding mmany local solvers don't
 * introduce a significant overhead to the whole system. General practice will be to have a higher resolution solver/sytem, more global. And then instantiate other ones 
 * for local and very optimized, quantized effects, and rename these properly, like "GlobalWavePhysics", "CharacterWavePhysics", "Battleground01WavePhysics", etc.
 * 
 * Phase 1: Basic System
* - Implement core wave propagation
* - Basic domain management
* - Simple thresholds

* Phase 2: Optimization Layer
* - Add streaming system
* - Implement LOD system
* - Setup caching

* Phase 3: Edge Case Handling
* - Dynamic thresholds
* - Anomaly detection
* - Effect generation

* Phase 4: Experimentation
* - Test extreme scenarios
* - Document emergent behaviors
* - Create gameplay features
* 
* Energy Density   → Adjust precision
* Activity Level   → Manage update rates
* Memory Usage     → Control streaming
* Solver Load      → Balance computations
* Edge Behaviors   → Generate effects
*/
#pragma once
#include <memory>

#include "ShortLivedParticle.h"
#include "Node.h"

namespace hd {

struct EnergyTransferInfo {
    // Progressive quantization levels
    struct Quantization {
        uint8_t highEnergy : 8;    // Full precision for critical areas
        uint8_t mediumEnergy : 6;  // Reduced for medium intensity
        uint8_t lowEnergy : 4;     // Minimal for background effects
    };

    // Energy transfer rules
    struct TransferRule {
        EnergyManifestationType::Type sourceType;
        EnergyManifestationType::Type targetType;
        float threshold;
        float conversionEfficiency;
        
        // Automatic reaction spawning
        struct Reaction {
            std::string effectTemplate;  // "explosion", "debris", "spark"
            float intensityScale;        // Scale effect by energy magnitude
            uint32_t particleCount;      // Dynamic particle count
            float lifetime;              // Effect duration
        } reaction;
    };
};

// Energy manifestation types and thresholds
struct EnergyManifestationType {
    enum class Type : uint8_t {
        KINETIC,        // Motion, velocity
        THERMAL,        // Heat, temperature
        DEFORMATION,    // Shape changes
        PARTICLE,       // Break-up, debris
        WAVE,          // Shock waves, ripples
        FIELD          // Electromagnetic, force fields
    };

    // Energy bands based on frequency ranges
    struct FrequencyBand {
        static constexpr float kRadioWaves     = 1e3f;    // Low energy EM
        static constexpr float kInfrared       = 1e12f;   // Thermal radiation
        static constexpr float kVisible        = 1e15f;   // Visible light
        static constexpr float kUltraviolet    = 1e16f;   // Starting to be harmful
        static constexpr float kXRay          = 1e18f;   // Ionizing radiation
        static constexpr float kGammaRay      = 1e20f;   // Highly penetrating
        static constexpr float kCosmicRay     = 1e24f;   // Ultra-high energy
    };

    // Interaction thresholds
    struct InteractionThreshold {
        static constexpr float kMolecularBond  = 1e-19f;  // Can break molecular bonds
        static constexpr float kIonization     = 1e-17f;  // Can ionize atoms
        static constexpr float kNuclearEffect  = 1e-13f;  // Can affect nuclear structure
        static constexpr float kParticleDecay  = 1e-10f;  // Can induce particle decay
    };
};

class WavePhysicsNode : public Node {
public:
    // === Structure Definitions ===
    struct WaveProperty {
        float amplitude;
        float frequency;
        float phase;
        vec3 propagationDirection;
        
        // Wave characteristics
        struct MediumInteraction {
            float wavelength;
            float attenuation;
            float dispersion;
            float penetration;      // Material penetration depth
            float ionizationRate;   // Rate of ionization effects
        } medium;
        
        // Effect properties based on frequency
        struct Effects {
            bool canIonize;
            bool canInduceMutation;
            bool canTriggerDecay;
            float chainReactionProbability;
        } effects;

        // Compute interaction effects based on frequency
        Effects calculateEffects() const {
            Effects e;
            e.canIonize = frequency >= FrequencyBand::kUltraviolet;
            e.canInduceMutation = frequency >= FrequencyBand::kXRay;
            e.canTriggerDecay = frequency >= FrequencyBand::kGammaRay;
            e.chainReactionProbability = 
                frequency >= FrequencyBand::kCosmicRay ? 
                    (frequency / FrequencyBand::kCosmicRay) : 0.0f;
            return e;
        }

        // Get penetration depth based on frequency
        float calculatePenetrationDepth(float materialDensity) const {
            // Higher frequencies penetrate deeper
            float basePenetration = std::log10(frequency) * 0.1f;
            return basePenetration / materialDensity;
        }
        
        // Dynamic precision based on amplitude
        uint32_t getBitDepth() const {
            if (amplitude > EnergyManifestationType::kHighEnergyThreshold) return 32;
            if (amplitude > EnergyManifestationType::kMediumEnergyThreshold) return 16;
            return 8;
        }
    };

    // Solver configuration for different physics layers
    struct SolverConfig {
        std::string name;  // e.g. "GlobalSolver", "CharacterSolver"
        float resolution;  // Spatial resolution for this solver
        uint32_t maxIterations;
        bool enableQuantization;
        float energyThreshold;
        // ... other solver-specific settings
    };

    // Inter-solver communication types
    enum class SolverMessageType {
        ENERGY_TRANSFER,
        WAVE_INTERACTION,
        FIELD_UPDATE,
        BOUNDARY_CONDITION,
        SOLVER_SYNC,
        PRIORITY_UPDATE
    };

    struct SolverMessage {
        SolverMessageType type;
        SolverId sourceSolver;
        SolverId targetSolver;
        
        // Packed message data using std::variant for type safety
        std::variant<
            EnergyTransferData,
            WaveInteractionData,
            FieldUpdateData,
            BoundaryConditionData,
            SolverSyncData,
            PriorityUpdateData
        > data;
        
        float priority;
        uint64_t timestamp;
    };

    // Message queue with priority handling
    class SolverMessageQueue {
    private:
        std::priority_queue<SolverMessage> m_queue;
        std::mutex m_queueMutex;
        
    public:
        void push(SolverMessage&& msg) {
            std::lock_guard<std::mutex> lock(m_queueMutex);
            m_queue.push(std::move(msg));
        }
        
        bool pop(SolverMessage& msg) {
            std::lock_guard<std::mutex> lock(m_queueMutex);
            if (m_queue.empty()) return false;
            msg = std::move(m_queue.top());
            m_queue.pop();
            return true;
        }
    };

    // Dynamic thresholds for energy management. Used consciously, only in situations where emergent dynamics, behaviors prove too
    // unreliable, umbearable, etc.
    struct DynamicThresholds {
        // Soft returns using sigmoid-like functions
        float smoothClamp(float value, float min, float max, float smoothness) {
            float range = max - min;
            float normalized = (value - min) / range;
            float sigmoid = 1.0f / (1.0f + exp(-normalized * smoothness));
            return min + (sigmoid * range);
        }
    
        // Energy level management
        struct EnergyBounds {
            float nominal;     // Expected operating range
            float warning;     // Start applying soft limits
            float critical;    // Apply stronger dampening
            float emergency;   // Hard clamp if needed
        } bounds;
    };

    // === Allocation, Initialization, Loading ===

    // Inter-solver communication methods
    void connectSolvers(SolverId source, SolverId target) {
        auto& sourceRef = m_solvers[source];
        auto& targetRef = m_solvers[target];
        
        // Register bidirectional connection
        m_solverConnections[source].push_back(target);
        m_solverConnections[target].push_back(source);
        
        // Setup shared boundary conditions
        setupSharedBoundary(sourceRef, targetRef);
    }

    void disconnectSolvers(SolverId source, SolverId target) {
        // Remove bidirectional connection
        auto& sourceConns = m_solverConnections[source];
        auto& targetConns = m_solverConnections[target];
        
        sourceConns.erase(
            std::remove(sourceConns.begin(), sourceConns.end(), target),
            sourceConns.end()
        );
        
        targetConns.erase(
            std::remove(targetConns.begin(), targetConns.end(), source),
            targetConns.end()
        );
    }

    // Send message between solvers
    void sendSolverMessage(SolverMessage&& msg) {
        if (!validateMessage(msg)) return;
        
        // Handle immediate messages
        if (msg.priority > 0.9f) {
            processSolverMessage(msg);
        } else {
            m_messageQueue.push(std::move(msg));
        }
    }

    // === Allocation, Initialization, Loading ===
    explicit WavePhysicsNode(const SolverConfig& config = SolverConfig()) 
        : Node(config.name), m_config(config) {}

    // === Processing ===
    // Energy transfer and transformation
    void transferEnergy(const vec3& position, float amount, 
                       EnergyManifestationType::Type sourceType,
                       EnergyManifestationType::Type targetType);
                       
    // Automatic reaction spawning
    void spawnReactions(const vec3& position, float energy);

    // Propagate wave from impact
    void propagateWave(const vec3& origin, const vec3& direction, float initialEnergy) {
        WaveProperty wave;
        wave.amplitude = initialEnergy;
        wave.propagationDirection = direction;
        wave.frequency = calculateInitialFrequency(initialEnergy);
        wave.effects = wave.calculateEffects();
        
        // Create wavefront tracker
        auto wavefront = m_particleSystem.createParticle(origin, initialEnergy);
        wavefront.pathType = ShortLivedParticle::Path::FIELD_GUIDED;
        
        // Consider frequency-dependent effects
        if (wave.effects.canTriggerDecay) {
            initializeDecayChain(wave);
        }
        
        // Register wave contribution with penetration effects
        float radius = calculateInfluenceRadius(initialEnergy);
        addWaveContribution(origin, radius, wave);
    }

    // Compute superposition at point
    float computeFieldStrength(const vec3& point) {
        float totalEnergy = 0.0f;
        
        for (const auto& wave : m_activeWaves) {
            // Consider phase and attenuation
            float distance = glm::length(point - wave.origin);
            float attenuation = calculateAttenuation(distance, wave.medium);
            float phaseShift = distance * wave.frequency;
            
            totalEnergy += wave.amplitude * attenuation * 
                          std::cos(phaseShift + wave.phase);
        }
        
        return totalEnergy;
    }

    // Handle wave interactions
    void processWaveInteractions() {
        for (const auto& wave : m_activeWaves) {
            // Check for constructive/destructive interference
            processInterference(wave);
            
            // Handle medium transitions
            processMediumBoundaries(wave);
            
            // Update wave properties based on field conditions
            updateWaveProperties(wave);
        }
    }

    // === Debugging & Visualization ===
    void debugVisualizeWave() {
        // Visualize wave propagation and interactions
        // for debugging and analysis
    }

    void debugVisualizeField() {
        // Visualize field strength and wave properties
        // for debugging and analysis
    }

    void debugVisualizeWavefronts() {
        // Visualize wavefronts and their propagation paths
        // for debugging and analysis
    }

    void debugVisualizeReactions() {
        // Visualize spawned reactions and their effects
        // for debugging and analysis
    }

private:
    // === Allocation, Initialization, Loading ===
    std::vector<WaveProperty> m_activeWaves;
    ShortLivedParticleSystem m_particleSystem;  // Used for wavefront tracking

    void initializeDecayChain(const WaveProperty& wave) {
        if (Random::Float() < wave.effects.chainReactionProbability) {
            // Spawn secondary radiation waves
            spawnSecondaryWaves(wave);
        }
    }

    // Create and configure a new solver instance
    SolverId createSolver(const SolverConfig& config) {
        auto solver = std::make_unique<WavePhysicsSolver>(config);
        SolverId id = m_nextSolverId++;
        m_solvers[id] = std::move(solver);
        return id;
    }

    void spawnSecondaryWaves(const WaveProperty& primary) {
        // Simulate particle decay or nuclear reactions
        // producing secondary radiation
    }

    void addWaveContribution(const vec3& origin, float radius, const WaveProperty& wave) {
        // Add wave contribution to the field
        // Consider medium properties and attenuation
    }

    // === Processing ===
    float calculateInitialFrequency(float initialEnergy) {
        // Map initial energy to frequency
        // Consider different manifestation types
        return initialEnergy * m_config.frequencyScale;
    }

    float calculateAttenuation(float distance, const WaveProperty::MediumInteraction& medium) {
        return std::exp(-distance * medium.attenuation);
    }

    float calculateInfluenceRadius(float initialEnergy) {
        // Determine influence radius based on energy
        return initialEnergy * m_config.radiusScale;
    }

    void processInterference(const WaveProperty& wave) {
        // Handle wave superposition and interference patterns
        // This affects energy distribution in the field
    }

    void processMediumBoundaries(const WaveProperty& wave) {
        // Handle reflection, refraction, and transmission
        // at medium boundaries
    }

    void updateWaveProperties(WaveProperty& wave) {
        // Adjust wave properties based on field conditions
        // and energy levels
    }

    // Process queued messages
    void processMessageQueue() {
        SolverMessage msg;
        while (m_messageQueue.pop(msg)) {
            processSolverMessage(msg);
        }
    }

    void processSolverMessage(const SolverMessage& msg) {
        auto& sourceSolver = m_solvers[msg.sourceSolver];
        auto& targetSolver = m_solvers[msg.targetSolver];
        
        switch (msg.type) {
            case SolverMessageType::ENERGY_TRANSFER: {
                const auto& data = std::get<EnergyTransferData>(msg.data);
                transferEnergyBetweenSolvers(sourceSolver, targetSolver, data);
                break;
            }
            case SolverMessageType::WAVE_INTERACTION: {
                const auto& data = std::get<WaveInteractionData>(msg.data);
                handleWaveInteraction(sourceSolver, targetSolver, data);
                break;
            }
            case SolverMessageType::FIELD_UPDATE: {
                const auto& data = std::get<FieldUpdateData>(msg.data);
                updateSharedField(sourceSolver, targetSolver, data);
                break;
            }
            // ... handle other message types
        }
    }

    void setupSharedBoundary(WavePhysicsSolver& source, WavePhysicsSolver& target) {
        // Create shared boundary region
        auto boundary = std::make_shared<BoundaryRegion>();
        boundary->resolution = std::min(source.getResolution(), target.getResolution());
        
        // Setup interpolation for different resolutions
        if (source.getResolution() != target.getResolution()) {
            boundary->setupInterpolation(
                source.getResolution(),
                target.getResolution()
            );
        }
        
        // Register boundary with both solvers
        source.addBoundaryRegion(boundary);
        target.addBoundaryRegion(boundary);
    }

    bool validateMessage(const SolverMessage& msg) {
        // Validate solver IDs exist
        if (!m_solvers.contains(msg.sourceSolver) || 
            !m_solvers.contains(msg.targetSolver)) {
            return false;
        }
        
        // Check if solvers are connected
        auto it = m_solverConnections.find(msg.sourceSolver);
        if (it == m_solverConnections.end()) return false;
        
        return std::find(it->second.begin(), 
                        it->second.end(), 
                        msg.targetSolver) != it->second.end();
    }
};

// Integration with ShortLivedParticleSystem
class WaveTrackingSystem {
public:
    // === Processing ===
    void updateWavePropagation(float deltaTime) {
        for (auto& particle : m_particleSystem.getActiveParticles()) {
            // Update wave properties
            auto& wave = m_energyField.getWaveAt(particle.currentPos);
            wave.amplitude *= calculateEnergyDissipation(particle, deltaTime);
            
            // Update propagation
            vec3 newDirection = calculateWaveDirection(particle, m_energyField);
            particle.velocity = newDirection * getWaveSpeed(wave);
            
            // Generate field effects
            if (particle.energy > m_config.minEnergyThreshold) {
                m_energyField.propagateWave(
                    particle.currentPos,
                    particle.velocity,
                    particle.energy
                );
            }
        }
    }

private:
    // === Processing ===
    float getWaveSpeed(const WaveProperty& wave) {
        return wave.frequency * wave.medium.wavelength;
    }

    vec3 calculateWaveDirection(const ShortLivedParticle& wavefront, 
                              const EnergyField& field) {
        // Consider field gradients and medium properties
        vec3 baseDirection = wavefront.velocity;
        vec3 fieldInfluence = field.getGradientAt(wavefront.currentPos);
        
        return glm::normalize(baseDirection + fieldInfluence * m_config.fieldInfluence);
    }

    ShortLivedParticleSystem m_particleSystem;
    EnergyField m_energyField;
    Config m_config;
};

// Energy as a dimensional field
class EnergyDimension {
public:
    // === Structure Definitions ===
    struct ExcitationField {
        // 4D noise field (3D space + energy dimension)
        float sampleField(const vec3& position, float energyLevel) const {
            // Warp the sampling based on energy level
            vec3 warpedPos = position + 
                vec3(simplex3D(position * energyLevel * m_warpFactor));
            
            // Multi-octave sampling for different energy scales
            float result = 0.0f;
            float amplitude = 1.0f;
            float frequency = m_baseFrequency;
            
            for(int i = 0; i < m_octaves; ++i) {
                result += amplitude * simplex4D(vec4(
                    warpedPos * frequency, 
                    energyLevel * m_energyScale
                ));
                
                frequency *= 2.0f;
                amplitude *= 0.5f;
            }
            
            return result;
        }

        // Optimization: Cache frequently accessed regions
        struct CachedRegion {
            BoundingBox bounds;
            float energyMin, energyMax;
            Grid3D<float> samples;
        };
        
        std::vector<CachedRegion> m_cachedRegions;
    };

    // Energy level as a dimensional value
    struct EnergySpectrum {
        vec4 spectralComponents;  // Different energy manifestations
        
        // Project to scalar when needed
        float toScalar() const {
            return glm::dot(spectralComponents, 
                           vec4(0.2f, 0.3f, 0.3f, 0.2f));  // Weighted projection
        }
        
        // Combine with field modulation
        EnergySpectrum modulate(float fieldValue) const {
            // Non-linear modulation based on field strength
            float modFactor = std::pow(1.0f + std::abs(fieldValue), 2.0f);
            return EnergySpectrum{spectralComponents * modFactor};
        }
    };

    // === Processing ===
    // Wave interaction with energy dimension
    struct ModulatedWave {
        WaveProperty baseProperties;
        EnergySpectrum energySpectrum;
        
        // Compute interaction with energy field
        void interact(const ExcitationField& field, const vec3& position) {
            float fieldValue = field.sampleField(position, 
                                               energySpectrum.toScalar());
            
            // Modulate wave properties based on field interaction
            EnergySpectrum modulated = energySpectrum.modulate(fieldValue);
            
            // Update wave characteristics
            baseProperties.frequency *= 
                1.0f + fieldValue * m_config.frequencyModulation;
            
            // Quantum effects at high energy levels
            if (modulated.toScalar() > FrequencyBand::kXRay) {
                triggerQuantumEffects(modulated);
            }
        }
    };

    void propagateModulatedWave(const vec3& origin, 
                               const vec3& direction, 
                               const EnergySpectrum& initialEnergy) {
        ModulatedWave wave;
        wave.energySpectrum = initialEnergy;
        wave.baseProperties = createBaseWaveProperties(initialEnergy);
        
        // Sample energy field at propagation points
        vec3 samplePoint = origin;
        float stepSize = m_config.propagationStepSize;
        
        while (wave.energySpectrum.toScalar() > m_config.minEnergyThreshold) {
            // Interact with energy dimension
            wave.interact(m_excitationField, samplePoint);
            
            // Update propagation
            samplePoint += direction * stepSize;
            
            // Generate field effects based on modulated energy
            if (shouldGenerateEffects(wave)) {
                generateFieldEffects(samplePoint, wave);
            }
        }
    }

private:
    // === Structure Definitions ===
    /**
     * @brief Solver for wave physics.
     * Internal solver class that handles actual physics calculations. WavePhysicsSolver is meant to be instantiated modularly, managed by WavePhysics, and allow for
     * different solver configurations, from the heavier global solvers to the more lightweight local, specialized, effects-oriented solvers.
     * We could have made it into a node, but we opted for an internal class to facilitate user workflow, communications between solvers - they're handled internally,
     * and directly, so we have the best of both worlds, as we can turn on and off connections between solvers, and have them communicate directly.
     */
    class WavePhysicsSolver {
        // TODO: 
        // - Implement the solver
        // - Allow, first of all, for different configurations, based on probable workflows, uses, and user preference. For this you'll resort to Vulkan-style
        // configuration info structs, and the implementation details themselves are handled internally.
        // - Methods, bridges to connect and disconnected transfer of data between solvers, safely.
    };

    // === Allocation, Initialization, Loading ===
    ExcitationField m_excitationField;
    float m_baseFrequency = 1.0f;
    float m_energyScale = 0.1f;
    float m_warpFactor = 0.5f;
    int m_octaves = 4;

    std::unordered_map<SolverId, std::unique_ptr<WavePhysicsSolver>> m_solvers;
    SolverId m_nextSolverId = 0;
    
    // === Processing ===
    void triggerQuantumEffects(const EnergySpectrum& energy) {
        // Handle high-energy quantum interactions
        // Like particle decay, pair production, etc.
    }
};

/**
 * @brief WaveBatchProcessor handles batch processing of waves.
 */
class WaveBatchProcessor {
    struct WaveBatch {
        // Packed wave properties for SIMD processing
        alignas(32) std::array<float, 8> amplitudes;
        alignas(32) std::array<float, 8> frequencies;
        alignas(32) std::array<float, 8> phases;
        alignas(32) std::array<vec3, 8> directions;
        
        // Metadata for batch processing
        uint32_t activeCount;
        uint32_t startIndex;
        
        // Optimization: Pre-calculated trigonometric values
        alignas(32) std::array<float, 8> sinValues;
        alignas(32) std::array<float, 8> cosValues;
    };

    // Process waves in SIMD-friendly batches
    void processBatch(WaveBatch& batch) {
        // Process 8 waves simultaneously using SIMD
        #pragma omp simd
        for (uint32_t i = 0; i < batch.activeCount; i++) {
            batch.amplitudes[i] *= std::exp(-decay * deltaTime);
            batch.phases[i] += batch.frequencies[i] * deltaTime;
            // Update pre-calculated trig values
            batch.sinValues[i] = std::sin(batch.phases[i]);
            batch.cosValues[i] = std::cos(batch.phases[i]);
        }
    }
};

/**
 * @brief FieldGridProcessor handles processing of field grids.
 */
class FieldGridProcessor {
    struct FieldBatch {
        // Dense grid representation for field values
        struct GridBlock {
            static constexpr uint32_t BLOCK_SIZE = 8;
            alignas(32) float values[BLOCK_SIZE][BLOCK_SIZE][BLOCK_SIZE];
            BoundingBox bounds;
            uint32_t resolution;
        };

        // Sparse octree for adaptive resolution
        struct OctreeNode {
            GridBlock block;
            std::array<std::unique_ptr<OctreeNode>, 8> children;
            float importance;  // For adaptive subdivision
        };

        // Compressed field representation
        struct CompressedField {
            // Wavelet compression for low-energy regions
            std::vector<float> coefficients;
            uint32_t compressionLevel;
            
            // Run-length encoding for homogeneous regions
            struct RLEBlock {
                float value;
                uint32_t count;
            };
            std::vector<RLEBlock> rleData;
        };
    };

    void processFieldBlock(GridBlock& block) {
        // Process 8x8x8 blocks using vectorized operations
        #pragma omp parallel for collapse(3)
        for (uint32_t x = 0; x < BLOCK_SIZE; x++) {
            for (uint32_t y = 0; y < BLOCK_SIZE; y++) {
                for (uint32_t z = 0; z < BLOCK_SIZE; z++) {
                    // SIMD-friendly field calculations
                }
            }
        }
    }
};

} // namespace hd






