[package]
title = "Hydragon Editor Core"
description = "Core functionality and monkeypatches for Hydragon Editor."
version = "0.1.0"
category = "Editor"
keywords = ["editor", "core"]

[dependencies]
"omni.kit.menu.utils" = {}
"omni.physx" = {}
"omni.timeline" = {}

[[python.module]]
name = "hydragon.editor.core"
