# Engine Configuration
engine:
  name: "Hydragon Engine"
  version: "alpha"
  company: "Agua Games"
  website: "https://aguagames.webflow.io/hydragon-engine-home"
  copyright_year: 2024
  license: "Agua Games License 1.0"

